language: java
matrix:
  include:
    - jdk: oraclejdk9

script: >-
  ./gradlew clean checkstyleMain checkstyleTest test coverage coveralls asciidoctor

deploy:
  skip_cleanup: true
  provider: script
  script: ./config/travis/deploy_github_pages.sh
  on:
    branch: master

addons:
  apt:
    packages:
      - oracle-java9-installer
