= Kian Hong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Restaurant Management System

Need to use more YOU statements

---

== Introduction

The purpose of this portfolio is to detail my contributions for the project.

The project is an idea that we have come up together with as a team as we aim to help improve the aims of Singapore or
wanting to be a smart nation.

Restaurant Management System is an application to help restaurants run more
efficiently and effectively by enhancing and automating different processes in the restaurant. From order taking to
employee management, many aspects of running a restaurant are covered.

The main features of the Restaurant Management System is Menu management, Order management, Employee management,
Member management and Statistics.

== Summary of contributions
|===
|_Given below are the contributions that I have done for the project._
|===

* *Major enhancement*: Added employee management features.
** What it does: Allows restaurant mangers using the system to list, add, edit and delete employees from the system. Additionally, employees of the restaurant can clock in and clock out their attendance in the system.
** Justification: This feature improves the product significantly because a restaurant manger can mange his/her employees in a more efficient way.
** Highlights: Needed to ensure that the commands implemented would be easy to understand and use for a non-tech savvy audience. The commands had to properly take care of invalid command formats and guide the user with examples on how to properly use the command when such invalid command formats are encountered.
** Credits: https://github.com/nusCS2113-AY1819S1/addressbook-level3

* *Code contributed*: https://github.com/CS2113-AY1819S1-F09-2/main[Project Github Page]

** Documentation:
*** Addition of content to User Guide: https://github.com/CS2113-AY1819S1-F09-2/main/pull/9[#9], https://github.com/CS2113-AY1819S1-F09-2/main/pull/82[#82], https://github.com/CS2113-AY1819S1-F09-2/main/pull/118[#118]
*** Addition of content to Developer Guide: https://github.com/CS2113-AY1819S1-F09-2/main/pull/91[#91], https://github.com/CS2113-AY1819S1-F09-2/main/pull/120[#120]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2113-AY1819S1-F09-2/main/pull/88[#88], https://github.com/CS2113-AY1819S1-F09-2/main/pull/99[#99], https://github.com/CS2113-AY1819S1-F09-2/main/pull/100[#100]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=employeecommands]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=UI]

include::../DeveloperGuide.adoc[tag=userstories]

include::../DeveloperGuide.adoc[tag=employeeusecase]
