= Neow Bo Kai - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ClassRepo

== Overview

ClassRepO is a desktop address book application written in Java that targets secondary schools for usage by their students, tutors and staff. This portfolio is meant to document the contributions that I made to the project.

== Roles
In this project, I serve mainly as a Code Quality checker. Aside from the code quality, I also ensure that the language used in the documentation is up to standard.

== Summary of contributions

* *Major enhancement*: added a new feature *Attendance*
** What it does: Allows the address book application to manage each student's attendance.
** Justification: This feature improves the product significantly as a school already needs to take the students' attendance. A digitalized storage and management of the attendance will make data analysis faster and also reduces the usage of paper (eco-friendly)
** Highlights: This feature requires editing of existing code as the additional field (attendance) for each person would mean that there will be a need to change portions of the code that are related to the person.
** Credits: (_to be updated_)

* *Minor enhancement*: (_to be updated_)

* *Other contributions*:

** Project management:
*** _to be updated_
** Enhancements to existing features:
*** (_to be updated_)(https://github.com[#insert PR no. here)
*** (_to be updated_) Wrote additional tests for existing features to increase coverage from _____% to _____%
** Documentation:
*** (_to be updated_) Reviewed grammar and spelling of documentation: https://github.com[#insert PR no. here]
** Community:
*** (_to be updated_) PRs reviewed (with non-trivial review comments): https://github.com[#insert PR no. here]
*** Contributed to forum discussions https://github.com[#insert PR no. here]
*** (_to be updated_) Reported bugs and suggestions for other teams in the class https://github.com[#insert PR no. here]


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

<<../UserGuide.adoc#attendance, Attendance Section>> +

include::../UserGuide.adoc[tag=attendance]

== Contributions to the Developer Guide
|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

<<./DeveloperGuide.adoc#attendance,Implementation of Attendance>>

include::../DeveloperGuide.adoc[tag=attendance]
