= Restaurant Management System (RMS) - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2113-AY1819S1-F09-2/main.git

By: `CS2113-AY1819S1-F09-2`      Since: `Aug 2018`      Licence: `MIT`

== Introduction

Food Management System is to help provide restaurants
 with a more efficient way to manage their restaurants.
  It has various amount of features that can improve
   productivity of the different staff members in the
    restaurant.
    Jump to the <<Quick Start>> to get started.

== Quick Start

*[Coming Soon]*

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*How It Works*

When the application is first started, users have to choose
 which state it wants to enter. There are 5 choices to pick from
 :

1. Menu

2. Order

3. Customers

4. Employees

5. Statistics

*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
====

=== Menu
==== View Menu

View all items inside the menu +
Format: view

* List the current food items in the menu

==== Find Menu

Finds the food item(s) related to the keywords typed in by the user. +
Format: find KEYWORD [MORE KEYWORDS]

* A list of menu items with names related to the keyword(s) will be displayed.
* The command is case insensitive.
* Order of keywords do not matter.

Example: +
find Burger COKE fries +
Returns Double Cheese Burger, Veggie Burger, Coke, Coke Zero, Fries, Curly Fries

==== Update Menu

Shows options that you can use to update the menu. +
Format: update

* Update Menu will show user what he/ she can do to update menu.
* Menu is updated by adding, editing or deleting food items from menu list.

==== Add Item

Add a new item to the menu and sorts the menu. +
Format: add NAME p/PRICE [t/TAG]

* Adds the new food item into the menu list

Example: +
add Cheese Fries p/3.50 t/New item +
System adds Cheese Fries to the existing menu.

==== Edit Item

Edit an item on the menu +
Format: edit INDEX [n/NAME] [p/PRICE] [t/TAG]

* Edits the name, price and tag of food item in that particular index (User able to edit either one or all three attributes of the particular food item)

Example: +
edit 3 Cheese Fries with bacon p/5.00 t/Limited Offer +
System updates Cheese Fries, which is in index 3, to Cheese Fries with bacon and changes the price from $3.50 to $5.00

==== Delete Item

Delete an item on the menu +
Format: delete INDEX

* Deletes the food item in that particular index

Example: +
view menu +
delete 1 +
System deletes food item in index 1 from the menu. +
find Cheese Fries +
Delete 3 +
System deletes Cheese Fries in index 3 from the menu.

=== Order
==== List Orders

Shows a list of all the current orders. +

Each order include details of: customer, ordered time, total price and the list of dish items and quantities ordered +

Only the non-private data of customer will be showed. +

Format: `listorder`

==== View Order

(To be implemented) +
Shows the details of a specified order. +
Format: view INDEX

* Edit the order at a specific index


==== Add Order

(To be implemented) +
Adds a new order to the list of current orders and display the list. +
Format: add ORDERFORMAT


==== Update Order

(To be implemented) +
Shows options that you can use to update orders. +
Format: update

* Shows the list of commands the user can use (add, edit, delete)


==== Edit Order

(To be implemented) +
Edit details of an order. +
Format: edit INDEX


* Edit the order at a specific index


==== Delete Order

Delete an order. +

The deleted order is specified by the index of that order on the last displayed order list. +

Format: `deleteorder INDEX`


==== Clear Order

Clear the entire order list. +

Format: `clearorder`


==== Find Order

(To be implemented) +
Find an order by certain parameters. +
Format: find KEYWORD [MORE_KEYWORDS]

* The search is case-insensitive
* The order of keywords do not matter
* Only the name of the order will be searched

=== Members

==== Add Member

Add a new member to the RMS +
Format: add NAME p/PHONE_NUMBER e/EMAIL_ADDRESS d/DATE_JOINED

==== Edit Member

Edit membership details of a member in the RMS +
Format: edit NAME [p/PHONE_NUMBER] [e/EMAIL_ADDRESS][d/DATE_JOINED][pt/POINTS]

===== Delete Member

Delete membership details of a member in the RMS +
Format: delete NAME

==== Find Member

Find membership details of a member in the RMS +
Format: find NAME


=== Employees
==== View Employees

Show a list of all the employees on the RMS. +
Format: view

==== Add Employee

Adds a new employee to the RMS. +
Format: add n/NAME p/PHONE_NUMBER pos/POSITION

Examples: +
add n/Joe Bob p/91234567 pos/Chef

==== Edit Employee

Edit details of an employee. +
Format: edit NAME [p/PHONE_NUMBER] [pos/POSITION]

* Edits the person with the given NAME.
* Parameters in square brackets are optional.
* At least one of the optional parameters must be provided.
* Existing values will be updated to the input values.

Examples: +
edit Joe Bob pos/Cashier +
Edits the value of Joe Bob to Cashier

=== Delete Employee

Delete and employee. +
Format: delete NAME

Examples: +
delete Joe Bob +
Deletes Joe Bob.

==== Calculate Wages

Calculates the wage of an employee. +
Format calcwage NAME

Examples: +
calcwage Joe Bob

=== Statistics

=== View Order Statistics

Display the order statistics overview +
Format: vieworderstats


=== View Member Statistics

Display the member statistics overview +
Format: viewmemberstats

=== Saving the data

Address book data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Restaurant Management System folder.

== Command Summary

=== Menu

*View Menu* : `view`

*Find Menu* : `find KEYWORD [MORE KEYWORDS]`

*Update Menu* : `update`

*Add Item* : `add NAME p/PRICE [t/TAG]`

*Edit Item* : `edit INDEX [n/NAME] [p/PRICE] [t/TAG]`

*Delete Item* : `delete INDEX`

=== Order

*List All Order* : `listorder`

*View Order* : `view INDEX`

*Add Order* : `add ORDERNAME`

*Update Order* : `update`

*Edit Order* : `edit INDEX`

*Delete Order* : `deleteorder INDEX`

*Clear Order* : `clearorder`

*Find Order* : `find KEYWORD [MORE_KEYWORDS]`

=== Employees

*View Employees* : `add n/NAME p/PHONE_NUMBER pos/POSITION`

*Add Employee* : `add n/NAME p/PHONE_NUMBER pos/POSITION`

*Edit Employee* : `edit NAME [p/PHONE_NUMBER] [pos/POSITION]`

*Delete Employee* : `delete NAME`

*Calculate Wages* : `calcwage NAME`

=== Members

*Add Member* : `add NAME p/PHONE_NUMBER e/EMAIL_ADDRESS d/DATE_JOINED`

*Edit Member* : `edit NAME [p/PHONE_NUMBER] [e/EMAIL_ADDRESS][d/DATE_JOINED][pt/POINTS]`

*Delete Member* : `delete NAME`

*Find Member* : `find NAME`

=== Statistics

*View Order Statistics* : `vieworderstats`

*View Member Statistics* : `viewmemberstats`